In [ ]:
-- Using the BicycleWeather.csv datasets to perform operations -->

In [1]:
import numpy as np

In [2]:
import pandas as pd
BicycleWeather = pd.read_csv('C:\\Python Class\\Datascience\\Datasets\\BicycleWeather.csv')
BicycleWeather.head()


STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  ...  WT17  WT05  WT02  WT22  \
0     0     0     0   128    50    47   100  ... -9999 -9999 -9999 -9999   
1   109     0     0   106    28    45   180  ... -9999 -9999 -9999 -9999   
2     8     0     0   117    72    23   180  ... -9999 -9999 -9999 -9999   
3   203     0     0   122    56    47   180  ... -9999 -9999 -9999 -9999   
4    13     0     0    89    28    61   200  ... -9999 -9999 -9999 -9999   

   WT04  WT13  WT16  WT08  WT18  WT03  
0 -9999 -9999 -9999 -9999 -9999 -9999  
1 -9999     1     1 -9999 -9999 -9999  
2 -9999 -9999     1 -9999 -9999 -9999  
3 -9999     1     1 -9999 -9999 -9999  
4 -9999 -9999     1 -9999 -9999 -9999  

[5 rows x 26 columns]

In [5]:
# Extraction of PRCP column from the pandas object.
Bicycle_weather = np.array(BicycleWeather['PRCP'])
print("PRCP \n",Bicycle_weather)

PRCP 
 [  0 109   8 ... 102   0  58]


In [14]:
#  using boolean functions/operators to separate numbers from NAN
Bicycle_weather
val = pd.notna(Bicycle_weather)
# Bicycle_weather[val]
val

array([ True,  True,  True, ...,  True,  True,  True])

In [23]:
#  using boolean masking to separate all zeros and non-zeros into different variables
zero = Bicycle_weather[val]
value = (zero == 0)
value2 = (zero != 0)
# zero[value]
print("All zeros: ", (zero[value]))
print("Non zeros: ", (zero[value2]))


All zeros:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 

In [35]:
# From the variable holding non-zeros, multiply every values in the array with 100 and divide by 250
(zero[value2]) * 100 / 250 

array([ 43.6,   3.2,  81.2,   5.2,  10. ,  17.2,   4. ,  16.4,  21.2,
        10. ,  32.4,  79.2,  60.8,  54. ,  12. ,  24.4,  34.4,  32.4,
        19.2, 110.8,  14.4,   7.2,  54. ,   1.2,  11.2,  10. ,  10. ,
         3.2,   4. ,  45.6,  10. ,   7.2,  69.2,  25.6,  12. ,   3.2,
        34.4,  45.6,   5.2,  14.4,   3.2,   8. ,  27.6,   2. ,  14.4,
        41.6,  54.8,  77.2,  37.6,  34.4,  95.6,  33.6,  37.6,  14.4,
         8. ,  14.4,   5.2,  16.4,  19.2,   5.2, 109.6,  22.4,  52.8,
         6. ,   6. ,  18.4,   1.2,   9.2,   2. ,  32.4,   7.2,   7.2,
        43.6,  26.4,  17.2,  42.8,  15.2,   3.2,  17.2,  17.2,   2. ,
         2. ,  74. ,   7.2,  25.6,  56. ,  24.4,   1.2,   1.2,  15.2,
        26.4,   1.2,   5.2,  64. ,  66. ,   6. ,   3.2,  12. ,   4. ,
        62.8,  34.4,   2. ,   1.2,  12. ,   8. ,  23.2,   6. ,   2. ,
         1.2,  60.8,   4. ,   1.2,   1.2,   1.2,   8. ,  19.2,  66. ,
        31.6,  83.2,  19.2,   2. ,  25.6,  35.6,  28.4,   6. ,  92.4,
        24.4,  43.6,